### ISSUE TITLE
Fix races in cos_kernel_api

### ISSUE THREAD

**Issue by gparmer** [gwsystems/composite#259] opened 2017-07-09 14:19 UTC
The `cos_kernel_api` currently uses bump pointers that are coordinated with kernel system calls for resource table construction, and memory mapping.  The current code has a number of issues:

1. No use of atomic instructions (add `faa` everywhere), and 
2. allow races on kernel APIs as concurrent threads might construct the same region of the resource table, thus return errors on `cons`.

So this issue will integrate `ps` into the `cos_kernel_api`, and update the code to understand that races are OK, so long as some thread's `cons` is successful (i.e. allow *helping*).

**Comment by Others** [comment] 2017-10-17 20:31
Duplicate of #261

**Closed by Others** 2017-10-17 20:31 UTC
Labels: C-infrastructure
